Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.network "public_network", bridge: "eno1", :mac => "000000000002"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "vm2"
    vb.cpus = 1
    vb.memory = "2048"
  end
  config.vm.provision "shell", privileged: true, inline: <<-SHELL
    apt-get install -y nfs-common
    echo "europa:/cluster /mnt nfs defaults" >> /etc/fstab
    mount -t nfs europa:/cluster /mnt
    tar xf /vagrant/OpenJDK8U-jdk_x64_linux_hotspot_8u232b09.tar.gz -C /opt
    tar xf /vagrant/spark-2.4.4-bin-hadoop2.7.tgz -C /opt
    ln -s /opt/jdk8u232-b09 /opt/jdk8
    ln -s /opt/spark-2.4.4-bin-hadoop2.7 /opt/spark
    echo "JAVA_HOME=/opt/jdk8" >> /etc/environment
    hostnamectl set-hostname vm2
    sed -i '/127\.0\.1\.1/d' /etc/hosts
    echo "192.168.1.102	vm2" >> /etc/hosts
  SHELL
  config.vm.provision "shell", privileged: false, inline: <<-SHELL
    cat /vagrant/vmcluster.id_rsa.pub >> /home/vagrant/.ssh/authorized_keys
    cp /vagrant/vmcluster.id_rsa /home/vagrant/.ssh/id_rsa
  SHELL
end

